# Generated by Django 3.0.1 on 2020-01-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_auto_20200101_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
